In [1]:
import torch
import numpy as np
import torch.nn as nn
X = torch.rand(4, 2, 3)
linear = nn.Linear(3, 2)

In [2]:
"""矩阵加法"""
# Z=W+X
W = torch.randn(4, 2, 3)
Z11 = W + X
print(Z11)
Z12 = W.add(X)
print(Z12)

tensor([[[-1.0051,  3.2258,  2.7636],
         [ 2.3868, -1.4041, -0.4409]],

        [[ 0.6413,  1.0061,  0.7203],
         [ 1.1332,  0.6712, -0.1710]],

        [[ 1.2816, -1.3223, -0.1568],
         [ 0.1846,  0.9827, -0.5908]],

        [[-0.1073,  1.7315, -1.2059],
         [-0.1545,  1.1422,  2.4506]]])
tensor([[[-1.0051,  3.2258,  2.7636],
         [ 2.3868, -1.4041, -0.4409]],

        [[ 0.6413,  1.0061,  0.7203],
         [ 1.1332,  0.6712, -0.1710]],

        [[ 1.2816, -1.3223, -0.1568],
         [ 0.1846,  0.9827, -0.5908]],

        [[-0.1073,  1.7315, -1.2059],
         [-0.1545,  1.1422,  2.4506]]])


In [25]:
a = torch.randn(100,1,3)
b = torch.randn(1,4, 3)
# print(a+ b)
print((a+b).size())

torch.Size([100, 4, 3])


In [4]:
# Z = WX -线性变换
Z2 = linear(X)
print('m.weight.shape:', linear.weight.shape) # 转置
print('m.bias.shape:', linear.bias.shape)
print('output.shape: ', Z2.shape)
print(Z2)
print(Z2.size())

m.weight.shape: torch.Size([2, 3])
m.bias.shape: torch.Size([2])
output.shape:  torch.Size([4, 2, 2])
tensor([[[-0.4093, -0.8356],
         [-0.6143, -0.6586]],

        [[-0.3648, -0.7702],
         [-0.6502, -0.7557]],

        [[-0.4306, -0.7892],
         [-0.0791, -0.8802]],

        [[-0.5188, -0.5493],
         [-0.4516, -0.6446]]], grad_fn=<AddBackward0>)
torch.Size([4, 2, 2])


In [5]:
# Z = W⊗X -矩阵外积 或 矩阵乘法[m,n]⊗[n,p]==[m,p]
mat1 = torch.randn(3, 4)
mat2 = torch.randn(4, 3)
print(torch.mm(mat1, mat2))

tensor([[-1.0963, -1.2870, -0.0705],
        [ 0.3586, -0.3665,  0.9191],
        [-1.3236, -7.5058, -3.9546]])


In [6]:
Z32 = np.outer(X, W2)
print(Z32)

NameError: name 'W2' is not defined

In [ ]:
Z33 = np.dot(X, W2)
print(Z33)

In [ ]:
Z34 = torch.dot()  # 仅能用于向量运算[1,n]⊗[n,1]
print(Z34)
# Z = W⊙X -矩阵元素积:即对应位置元素相乘[m,n]⊙[m,n]==[m,n]

In [ ]:
Z41 = torch.mul(X, W)
print(Z41)

In [ ]:
Z43 = W * X  # 若W和X是torch.tensor，同样是元素积
print(Z43)

In [ ]:
Z42 = np.multiply(X, W)
print(Z42)

In [ ]:
# torch.mv

In [ ]:
https://www.jianshu.com/p/234bc2a533c7