In [1]:
import torch
x = torch.Tensor([1, 2, 3, 4])  # torch.Tensor是默认的tensor类型（torch.FlaotTensor）的简称。
print(x)  # tensor([1., 2., 3., 4.])
print(x.size())  # torch.Size([4])
print(x.dim())  # 1
print(x.numpy())  # [1. 2. 3. 4.]

tensor([1., 2., 3., 4.])
torch.Size([4])
1
[1. 2. 3. 4.]


# Unsqueeze
+ 不改变原始数据

In [2]:
print(torch.unsqueeze(x, 0))  
print(x)
print(torch.unsqueeze(x, 1)) 
print(x)
print(torch.unsqueeze(x, -1)) 
print(x)
print(torch.unsqueeze(x, -2)) 
print(x)

tensor([[1., 2., 3., 4.]])
tensor([1., 2., 3., 4.])
tensor([[1.],
        [2.],
        [3.],
        [4.]])
tensor([1., 2., 3., 4.])
tensor([[1.],
        [2.],
        [3.],
        [4.]])
tensor([1., 2., 3., 4.])
tensor([[1., 2., 3., 4.]])
tensor([1., 2., 3., 4.])


# Unsqueeze_
+ 改变原始数据

In [3]:
print(x.unsqueeze_(0))  
print(x)

tensor([[1., 2., 3., 4.]])
tensor([[1., 2., 3., 4.]])


# Squeeze
+ 不改变原始数据

In [4]:
print(x)
print(x.squeeze(-1))
print(x)
print(x.squeeze(-2))

tensor([[1., 2., 3., 4.]])
tensor([[1., 2., 3., 4.]])
tensor([[1., 2., 3., 4.]])
tensor([1., 2., 3., 4.])


# Squeeze_
+ 改变原始数据

In [5]:
print(x)
print(x.squeeze_(-1))
print(x)
print(x.squeeze(-1))

tensor([[1., 2., 3., 4.]])
tensor([[1., 2., 3., 4.]])
tensor([[1., 2., 3., 4.]])
tensor([[1., 2., 3., 4.]])


In [6]:
print(x)
print(x.squeeze_(-2))

tensor([[1., 2., 3., 4.]])
tensor([1., 2., 3., 4.])
