In [1]:
import torch
a = torch.ones((2, 3))
a1 =  torch.sum(a)
a2 =  torch.sum(a, dim=0)
a3 =  torch.sum(a, dim=1)
print(a)
print(a1)
print(a2)
print(a3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor(6.)
tensor([2., 2., 2.])
tensor([3., 3.])


In [6]:
 a = [ [1, 1, 1, 0,0], [1, 0, 0, 0,0] ]
 print(a)
 print(torch.Tensor(a).sum(1))
 print(torch.Tensor(a).sum(0))

[[1, 1, 1, 0, 0], [1, 0, 0, 0, 0]]
tensor([3., 1.])
tensor([2., 1., 1., 0., 0.])
