用hmmlearn学习隐马尔科夫模型HMM https://www.cnblogs.com/pinard/p/7001397.html

+ hmmlearn https://www.jianshu.com/p/b7758d4a59ca
    + GaussianHMM：观测状态是连续状态，且符合高斯分布
    + GMMHMM：观测状态是连续状态，且符合混合高斯分布
    + MultinomialHMM：观测状态是离散的


In [12]:
import numpy as np
from hmmlearn import hmm

states = ["box 1", "box 2", "box3"]
n_states = len(states)
observations = ["red", "white"]
n_observations = len(observations)
start_probability = np.array([0.2, 0.4, 0.4])
transition_probability = np.array([
  [0.5, 0.2, 0.3],
  [0.3, 0.5, 0.2],
  [0.2, 0.3, 0.5]
])
emission_probability = np.array([
  [0.5, 0.5],
  [0.4, 0.6],
  [0.7, 0.3]
])
model = hmm.MultinomialHMM(n_components=n_states)
model.startprob_=start_probability
model.transmat_=transition_probability
model.emissionprob_=emission_probability

seen = np.array([[0,1,0]]).T
logprob, box = model.decode(seen, algorithm="viterbi")
print("The ball picked:", ", ".join(map(lambda x: observations[x], seen.flatten())))
print("The hidden box", ", ".join(map(lambda x: states[x], box)))

The ball picked: red, white, red
The hidden box box3, box3, box3


In [13]:
box2 = model.predict(seen)
print("The ball picked:", ", ".join(map(lambda x: observations[x], seen.flatten())))
print("The hidden box", ", ".join(map(lambda x: states[x], box2)))

The ball picked: red, white, red
The hidden box box3, box3, box3


In [14]:
import numpy as np
from hmmlearn import hmm
states = ["box 1", "box 2", "box3"]
n_states = len(states)
observations = ["red", "white"]
n_observations = len(observations)
model2 = hmm.MultinomialHMM(n_components=n_states, n_iter=20, tol=0.01)
X2 = np.array([[0,1,0,1],[0,0,0,1],[1,0,1,1]])
model2.fit(X2)
print(model2.startprob_)
print(model2.transmat_)
print(model2.emissionprob_)
print(model2.score(X2))
model2.fit(X2)
print(model2.startprob_)
print(model2.transmat_)
print(model2.emissionprob_)
print(model2.score(X2))

Even though the 'startprob_' attribute is set, it will be overwritten during initialization because 'init_params' contains 's'
Even though the 'transmat_' attribute is set, it will be overwritten during initialization because 'init_params' contains 't'
[0.31234156 0.4501524  0.23750604]
[[0.33484524 0.3200893  0.34506546]
 [0.33541825 0.31462262 0.34995913]
 [0.33445689 0.32363219 0.34191092]]
[[0.49118293 0.50881707]
 [0.57282152 0.42717848]
 [0.43726572 0.56273428]]
-8.284680865193941
[1.68947043e-15 9.99999973e-01 2.70803779e-08]
[[2.71169935e-01 5.67465589e-01 1.61364476e-01]
 [7.49276085e-01 5.14150175e-05 2.50672500e-01]
 [1.67811621e-01 6.46116406e-01 1.86071973e-01]]
[[0.12263025 0.87736975]
 [0.99893129 0.00106871]
 [0.29912917 0.70087083]]
-6.557910459006066


In [15]:
startprob = np.array([0.6, 0.3, 0.1, 0.0])
# The transition matrix, note that there are no transitions possible
# between component 1 and 3
transmat = np.array([[0.7, 0.2, 0.0, 0.1],
                     [0.3, 0.5, 0.2, 0.0],
                     [0.0, 0.3, 0.5, 0.2],
                     [0.2, 0.0, 0.2, 0.6]])
# The means of each component
means = np.array([[0.0,  0.0],
                  [0.0, 11.0],
                  [9.0, 10.0],
                  [11.0, -1.0]])
# The covariance of each component
covars = .5 * np.tile(np.identity(2), (4, 1, 1))

# Build an HMM instance and set parameters
model3 = hmm.GaussianHMM(n_components=4, covariance_type="full")

# Instead of fitting it from the data, we directly set the estimated
# parameters, the means and covariance of the components
model3.startprob_ = startprob
model3.transmat_ = transmat
model3.means_ = means
model3.covars_ = covars