In [1]:
import torch
import numpy as np
import torch.nn as nn
X = torch.rand(4, 2, 3)
linear = nn.Linear(3, 2)

In [2]:
"""矩阵加法"""
# Z=W+X
W = torch.randn(4, 2, 3)
Z11 = W + X
print(Z11)
Z12 = W.add(X)
print(Z12)

tensor([[[ 0.9186, -0.3765,  0.4423],
         [ 1.7198, -0.5856,  2.2011]],

        [[ 3.0685,  1.2498,  0.2652],
         [-1.0613,  1.3680,  1.0349]],

        [[-0.5844,  1.4049, -0.9892],
         [ 0.4554, -0.8827,  0.7376]],

        [[-1.3316,  0.9583,  1.6431],
         [ 1.6169,  0.1097,  1.3837]]])
tensor([[[ 0.9186, -0.3765,  0.4423],
         [ 1.7198, -0.5856,  2.2011]],

        [[ 3.0685,  1.2498,  0.2652],
         [-1.0613,  1.3680,  1.0349]],

        [[-0.5844,  1.4049, -0.9892],
         [ 0.4554, -0.8827,  0.7376]],

        [[-1.3316,  0.9583,  1.6431],
         [ 1.6169,  0.1097,  1.3837]]])


In [3]:
# Z = WX -线性变换
Z2 = linear(X)
print('m.weight.shape:', linear.weight.shape) # 转置
print('m.bias.shape:', linear.bias.shape)
print('output.shape: ', Z2.shape)
print(Z2)
print(Z2.size())

m.weight.shape: torch.Size([2, 3])
m.bias.shape: torch.Size([2])
output.shape:  torch.Size([4, 2, 2])
tensor([[[ 0.2914,  0.3519],
         [ 0.5140,  0.2017]],

        [[ 0.5664,  0.3679],
         [ 0.3865,  0.2624]],

        [[ 0.1989,  0.0686],
         [ 0.3195,  0.3033]],

        [[ 0.2729, -0.0330],
         [ 0.4813,  0.2752]]], grad_fn=<AddBackward0>)
torch.Size([4, 2, 2])


In [4]:
# Z = W⊗X -矩阵外积 或 矩阵乘法[m,n]⊗[n,p]==[m,p]
mat1 = torch.randn(3, 4)
mat2 = torch.randn(4, 3)
print(torch.mm(mat1, mat2))

tensor([[-0.9668,  0.7569,  0.6088],
        [-0.0878,  0.7401, -0.1278],
        [ 0.1125,  1.9346,  1.9470]])


In [5]:
Z32 = np.outer(X, W2)
print(Z32)

NameError: name 'W2' is not defined

In [ ]:
Z33 = np.dot(X, W2)
print(Z33)

In [ ]:
Z34 = torch.dot()  # 仅能用于向量运算[1,n]⊗[n,1]
print(Z34)
# Z = W⊙X -矩阵元素积:即对应位置元素相乘[m,n]⊙[m,n]==[m,n]

In [ ]:
Z41 = torch.mul(X, W)
print(Z41)

In [ ]:
Z43 = W * X  # 若W和X是torch.tensor，同样是元素积
print(Z43)

In [ ]:
Z42 = np.multiply(X, W)
print(Z42)

In [ ]:
# torch.mv

In [ ]:
https://www.jianshu.com/p/234bc2a533c7