### Dirichlet Function
$f(x)=\left\{\begin{array}{ll}1, & \text { x为有理数 } \\ 0, & \text { x为无理数 }\end{array}\right.$

### Dirichlet Distribution
+ $f(x)=\frac{1}{\mathrm{~B}(\boldsymbol{\alpha})} \prod_{i=1}^{K} x_{i}^{\alpha_{i}-1}$, 其中 $\mathrm{B}(\boldsymbol{\alpha})=\frac{\prod_{i=1}^{K} \Gamma\left(\alpha_{i}\right)}{\Gamma\left(\sum_{i=1}^{K} \alpha_{i}\right)}$， $\sum_{i=1}^{K} x_{i} \leq 1$

In [16]:
from scipy.stats import dirichlet
import numpy as np 
quantiles = np.array([0.18, 0.22, 0.6])  # specify quantiles
alpha = np.array([1, 1, 12])  # specify concentration parameters
print(dirichlet.pdf(quantiles, alpha))
print(dirichlet.mean(alpha))  # get the mean of the distribution
print(dirichlet.var(alpha)) # get variance
print(dirichlet.entropy(alpha))  # calculate the differential entropy

0.5659634073599982
[0.07142857 0.07142857 0.85714286]
[0.00442177 0.00442177 0.00816327]
-3.287035494429027


In [17]:
from scipy.stats import dirichlet
import numpy as np 
quantiles = np.array([0.17, 0.22, 0.61])  # specify quantiles
alpha = np.array([1, 1, 12])  # specify concentration parameters
print(dirichlet.pdf(quantiles, alpha))
print(dirichlet.mean(alpha))  # get the mean of the distribution
print(dirichlet.var(alpha)) # get variance
print(dirichlet.entropy(alpha))  # calculate the differential entropy

0.6788171147383972
[0.07142857 0.07142857 0.85714286]
[0.00442177 0.00442177 0.00816327]
-3.287035494429027


### Reference
+ https://baike.baidu.com/item/%E7%8B%84%E5%88%A9%E5%85%8B%E9%9B%B7%E5%88%86%E5%B8%83

In [ ]:
DP的后验分布是CRP
https://zhuanlan.zhihu.com/p/78743630

In [ ]:
结论2：Dirichlet分布就是由2种结果bernoulli trial导出的Beta分布外推到k种的一般情形。

详细一点地说，二项分布的分布是Beta分布，而二项分布的推广形式多项分布的分布就是Dirichlet分布。
https://xijunlee.github.io/2017/09/09/Dirichlet%E5%88%86%E5%B8%83%E4%B8%8EBeta%E5%88%86%E5%B8%83/