In [1]:
import torch

X = torch.randn(2,3,4) # batch_size, sequence_length, embedding_dim
print(X)
print(X.size())

tensor([[[-0.9967, -0.9330, -0.0326, -0.4899],
         [ 0.4179,  0.4514,  0.0839,  3.0982],
         [ 3.3712,  2.2387,  0.7966, -0.6468]],

        [[-2.0937,  1.1803,  0.9583, -1.3858],
         [-0.5227,  0.6232, -0.3494, -0.4605],
         [-0.1747, -0.5465,  0.5057,  0.8110]]])
torch.Size([2, 3, 4])


In [2]:
import sys

sys.path.append('..')
from function.modeling import AttentionSelf

self_att = AttentionSelf(4, 100, 5) # embedding_dim, dim_k, dim_v
res = self_att(X)
print(res)
print(res.size())

tensor([[[-0.0324, -0.1149, -0.0419, -0.1556, -0.2403],
         [-0.0262, -0.0608, -0.0163, -0.1013, -0.1576],
         [-0.0099,  0.0821, -0.0259, -0.1905,  0.0177]],

        [[-0.0239,  0.0768,  0.0303, -0.0546,  0.0119],
         [-0.0138,  0.0477,  0.0395, -0.0445, -0.0021],
         [-0.0533,  0.0566,  0.2021, -0.0471, -0.0657]]],
       grad_fn=<BmmBackward>)
torch.Size([2, 3, 5])


In [3]:
import sys

sys.path.append('..')
from function.modeling import AttentionMulitHead

self_att = AttentionMulitHead(4, 100, 5) # embedding_dim, dim_k, dim_v
res, score = self_att(X,X)
print(res)
print(res.size())
print(score)

tensor([[[ 0.3305, -0.6529, -0.1530,  0.3678, -0.9866],
         [-0.1778, -0.4165,  0.3536, -0.1222,  0.1489],
         [ 0.4404, -0.2942, -0.0023,  0.2176, -0.3609]],

        [[ 0.0463, -0.4390,  0.1155,  0.0371, -0.3586],
         [ 0.0091, -0.1093,  0.3935,  0.3817,  0.2474],
         [-0.0126,  0.1208,  0.4828,  0.5225,  0.4313]]],
       grad_fn=<AddBackward0>)
torch.Size([2, 3, 5])
tensor([[[1.2051e-01, 8.7831e-01, 1.1845e-03],
         [9.9998e-01, 1.9148e-05, 1.1398e-08],
         [2.4400e-05, 8.9651e-20, 9.9998e-01]],

        [[2.3499e-04, 4.2739e-02, 9.5703e-01],
         [5.5140e-01, 3.8284e-01, 6.5763e-02],
         [9.8708e-01, 7.0562e-03, 5.8604e-03]]], grad_fn=<SoftmaxBackward>)
