https://blog.csdn.net/york1996/article/details/81949843

In [1]:
import torch

a=torch.Tensor([[[1,2,3],[4,5,6]]])
b=torch.Tensor([1,2,3,4,5,6])

print(a.view(1,6))
print(b.view(1,6))

tensor([[1., 2., 3., 4., 5., 6.]])
tensor([[1., 2., 3., 4., 5., 6.]])


In [2]:
import torch

a=torch.Tensor([[[1,2,3],[4,5,6]]])
print(a.view(-1,1,2))

tensor([[[1., 2.]],

        [[3., 4.]],

        [[5., 6.]]])
